### PR TITLE
Adding @var User instance comment to avoid intelliphense error (attached below)

### PR DESCRIPTION
**Pull request by pussy-cats**
Hi Will,
I'm Amardika Mahdi Pradana, college student from Indonesia.

I really excited about this project, and looking forward to make contributions to this repo.
Feel free to review my codes, this is for my first introduction. I will look at the project more when i have my spare time, and hopes i can contribute more to this project.

Best Regards,
Amardika Mahdi Pradana

<details>
<summary>Screenshot</summary>
Screenshot 2022-11-22 at 14 52 29

</details>

### CODE REVIEW

**Review by WillTheDeveloper — APPROVED** [review]

**Comment by WillTheDeveloper** [comment]
Hey!

Looks good to me. Thanks for the contribution, much appreciated.  That is awesome that you are excited about this project! It will be awesome once this repository gets some more recognition with some more contributors on it.

Something I will mention is that the README is slightly outdated so if you see anything on it that seems wrong or unsure about, please create an issue and ask :)

Kind Regards
Will

**Comment by pussy-cats** [comment]
Thanks for the reply and the merge Will, happy to contribute to this project!

I saw the issue that you haven't implement the third-party auth yet?
Can i work on it?

**Comment by pussy-cats** [comment]
If yes, please assign me to work on it, so i can monitor it on my Github too!

**Comment by WillTheDeveloper** [comment]
Yeah, sure.

I have already sort of implemented GitHub third party auth but kinda fell apart because a user requires a password and when I did it, there was no password in the registration flow.

I might remove spotify from this list but if you like, I can assign this task to you from the official roadmap?

https://github.com/Study-Portal/roadmap/issues/12

**Comment by WillTheDeveloper** [comment]
@pussy-cats Could you accept the invitation to the org so I can assign it :) https://github.com/orgs/Study-Portal/teams/developers

**Comment by WillTheDeveloper** [comment]
At some point I will move this repo to the official org

**Comment by pussy-cats** [comment]
> @pussy-cats Could you accept the invitation to the org so I can assign it :) https://github.com/orgs/Study-Portal/teams/developers

sadly it's 404 Will, is it privated?

**Comment by WillTheDeveloper** [comment]
You should have received an email about it buddy, check your emails

**Comment by pussy-cats** [comment]
It is there on my emails, setting up my 2FA, will follow up later

**Comment by WillTheDeveloper** [comment]
Awesome sauce! Feel free to assign yourself tasks too.

**Pull request merged**
