### PR TITLE
OwnerOnly Middleware

### PR DESCRIPTION
**Pull request by Gruce**
OwnerOnly middleware and applied to Kanban delete

### CODE REVIEW

**Comment by WillTheDeveloper** [comment]
@Gruce Do you think since its only for one or two post methods that instead of making a whole middleware dedicated for it, what if we just added it to the controller that handles the requests?

Don't get me wrong, what you have done it awesome once I figured out what you changed.

Futhermore, not sure if it was done by accident or not, app.js and app.css has changed?

**Comment by Gruce** [comment]
If we add it to the controller then it would not be reusable and can cause duplication in the code, since user_id (as owner) could be in multiple Models (like post, blog, etc..). We can improve it by making another option for admins.

About `app.css` and `app.js` once I executed `npm run dev` it has recompiled css files and js files. It could be skipped or maybe gitignore it.

**Comment by Gruce** [comment]
I think we could also make group routes and assign this middleware to it, it would be more readable, I think.

**Review by WillTheDeveloper — COMMENTED** [review]
Looks good. Just going to double make sure everything is okay since your the first totally outside collaborator.

**Review by WillTheDeveloper — APPROVED** [review]

**Pull request merged**
